version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: servicedesk_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: servicedesk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
